name: Code Coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: arielavi/cpp-env:build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and measure
        run: sh ci/coverage.sh

      - name: Archive Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage_reports
          path: coverage.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info
          fail_ci_if_error: true
          functionalities: fixes