name: Code Coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: arielavi/cpp-env:build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pip
        run: apt-get update && apt-get install -y python3-pip

      - name: install gcovr
        run: pip install gcovr==5.0 #5.1 not supported

      - name: Configure CMake
        run: cmake -S . -B build/coverage/ -DCMAKE_BUILD_TYPE="Coverage"

      - name: Build
        run: cmake --build build/coverage/

      - name: Build and measure
        run: sh ci/coverage.sh

      - name: Archive Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage_reports
          path: coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
          functionalities: fixes