name: Code Coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: arielavi/cpp-env:build-boost

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build (Coverage)
        run: cmake --build build --config Debug --target minimacore_coverage

      - name: Archive Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage_reports
          path: build/mbsolve_coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: build/mbsolve_coverage.info
          fail_ci_if_error: true
          functionalities: fixes