name: Run Unit Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: arielavi/cpp-env:build-boost

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build/tests --config Release --target minimacore_tests

      - name: Run Tests
        run: ctest --test-dir build/tests -C Release --output-junit out.xml

      - name: Archive Test Outputs
        uses: actions/upload-artifact@v2
        with:
          name: mbsolve_tests_report
          path: build/tests/out.xml